### ISSUE TITLE
Support MacBookPro10,1

### ISSUE THREAD

**Issue by jhnkane** [MuertoGB/MacEfiToolkit#17]
thank you for the tool.

sorry , maybe this is not an "issue" , however , **MBP101.scap is not detected as a valid firmware image**.

(or "flashrom -p internal -r dump.bin")

BaseBoard Product	Mac-C3EC7CD22292981F
BIOS Version/Date	Apple Inc. 429.0.0.0.0, 3/18/2022
System Model	MacBookPro10,1

i see #features reads, "UEFI version from 2013 onwards".

is this expected? maybe "early 2013" is not supported. thanks again.

**Comment by MuertoGB** [comment]
MacEfiToolkit cannot currently handle .scap images, nor do I know how the formatting of a .scap file works. This is something I may invest time into in the future.
