### ISSUE TITLE
how to open scap/fd files thx

### ISSUE THREAD

**Issue by kocoman2** [MuertoGB/MacEfiToolkit#6]
how to open scap/fd files thx

**Comment by MuertoGB** [comment]
Could you please provide more context. Do you mean files with those extensions,in this application?

**Comment by kocoman2** [comment]
https://github.com/gdbinit/firmware_vault/tree/master/EFI/MacBookPro

**Comment by MuertoGB** [comment]
Mac EFI Toolkit does not support capsule files, it supports previously dumped firmware. When opening a file, select 'All Files' from the drop down menu in the open file dialog.

![example](https://github.com/MuertoGB/MacEfiToolkit/assets/114369357/4163cffc-89ad-4c28-9f5b-5d18e44611b8)
